### ISSUE TITLE
Crashes when receiving notification

### ISSUE THREAD

**Issue by dcartertwo** [oceans15/teleport#52]
To replicate (in android-notifications branch)
-Start the app
-Push notification
-Close app
-Reopen app

The app crashes after a second or instantly.  Running adb logcat i found:
```
E/AndroidRuntime(  424): FATAL EXCEPTION: main
E/AndroidRuntime(  424): Process: com.oceans15.channel37, PID: 424
E/AndroidRuntime(  424): java.lang.RuntimeException: Unable to instantiate receiver com.parse.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.parse.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.oceans15.channel37-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.oceans15.channel37-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(  424): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2518)
E/AndroidRuntime(  424): 	at android.app.ActivityThread.access$1800(ActivityThread.java:161)
E/AndroidRuntime(  424): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
E/AndroidRuntime(  424): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(  424): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(  424): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
E/AndroidRuntime(  424): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  424): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(  424): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
E/AndroidRuntime(  424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/AndroidRuntime(  424): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(  424): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.parse.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.oceans15.channel37-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.oceans15.channel37-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(  424): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
E/AndroidRuntime(  424): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(  424): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(  424): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2513)
E/AndroidRuntime(  424): 	... 10 more
W/ActivityManager(  817):   Force finishing activity com.oceans15.channel37/.CordovaApp
```

Not sure why the java class isn't getting instantiated properly.

**Comment by dcartertwo** [comment]
FIXED on android
